config:
  mon_type: icinga
icinga:
  prod:
    host: '192.168.5.160'
    port: '80'
    proto: 'http'
    auth_key: 'Z0ZcM7B4UOYfALLmLNhEdXkW5Ro'
openstack:
    vcpus_allocation_ratio: 2.0
    ram_allocation_ratio: 1.0
    # remove this amount per node available metric
    reserved_ram_per_node: 0
    reserved_vcpus_per_node: 0
    # remove this amount from total
    reserved_ram: 0
    reserved_vcpus: 0
    # use neutron quotas (overwrites default limits call)
    neutron_quotas: false
#nagios:
#  prod:
#    url: 'http://my-prod-nagios/cgi-bin/nagios3/'
#    username: 'nagios'
#    password: 'nagios'
aviator:
  provider: openstack
  auth_service:
    name: identity
    host_uri: 'https://api1.example.com:5000'
    request: create_token
    validator: list_tenants
    api_version: v2
  auth_credentials:
    username: 'admin'
    password: '123456'
    tenant_name: 'openstack'
