config:
  mon_type: nagios
openstack:
    vcpus_allocation_ratio: 2.0
    ram_allocation_ratio: 1.0
    # remove this amount per node available metric
    reserved_ram_per_node: 0
    reserved_vcpus_per_node: 0
    # remove this amount from total
    reserved_ram: 0
    reserved_vcpus: 0
    # use neutron quotas (overwrites default limits call)
    neutron_quotas: false
nagios:
  prod:
    url: 'http://10.49.57.77/nagios/'
    username: 'nagiosadmin'
    password: 'nagiosadmin'
aviator:
  provider: openstack
  auth_service:
    name: identity
    host_uri: 'https://api1.example.com:5000'
    request: create_token
    validator: list_tenants
    api_version: v2
  auth_credentials:
    username: 'admin'
    password: '123456'
    tenant_name: 'openstack'
